const qs=[
{title:'Detecta el problema',type:'reviews',question:'Analiza estas reseñas. ¿Qué problema aparece de forma recurrente?',reviews:[['★★★★★','La habitación estuvo impecable y el personal fue muy amable.'],['★★★☆☆','El hotel es bonito, pero tardaron demasiado en hacer mi check-in.'],['★★★★★','Excelente experiencia, especialmente el servicio del restaurante.'],['★★☆☆☆','La atención fue buena, pero tuve que esperar mucho para entrar.']],options:['Demoras en el check-in','Problemas con el restaurante','Limpieza deficiente','Decoración del hotel'],answer:0,ok:'Correcto. Dos reseñas mencionan tiempos de espera al llegar.',bad:'Observa las reseñas: el patrón se relaciona con el tiempo de espera en recepción.'},
{title:'Toma una decisión',question:'El problema principal son las demoras en recepción. ¿Qué acción responde directamente al problema?',options:['Reforzar el personal de recepción durante las horas de mayor llegada.','Ignorar las reseñas porque también existen comentarios positivos.','Reducir el horario de recepción.','Eliminar el registro de llegada del hotel.'],answer:0,ok:'Correcto. La acción responde directamente al problema detectado.',bad:'La acción debe estar relacionada directamente con las demoras de check-in.'},
{title:'Elige el KPI',type:'kpi',question:'¿Qué indicador permitiría comprobar si disminuyeron las demoras?',options:[['↓ 18%','Tiempo promedio de check-in'],['4.7 ★','Rating promedio'],['92%','Ocupación']],answer:0,ok:'Correcto. El tiempo promedio de check-in mide directamente la mejora.',bad:'Busca un indicador que mida directamente las demoras que quieres reducir.']}];
let r=0,score=0,rep=40,timer;
const $=id=>document.getElementById(id);
function show(id){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');}
function start(){r=0;score=0;rep=40;$('score').textContent=0;render();}
function render(){const q=qs[r];$('round').textContent=`Ronda ${r+1} de 3`;$('title').textContent=q.title;$('bar').style.width=((r+1)/3*100)+'%';$('feedback').className='';$('next').classList.add('hidden');let h=`<p class="question-sub">${q.question}</p>`;if(q.type==='reviews'){h+='<div class="reviewgrid">';q.reviews.forEach(x=>h+=`<article class="review"><div class="stars">${x[0]}</div><p>“${x[1]}”</p></article>`);h+='</div>'}h+=`<div class="${q.type==='kpi'?'kpis':'options'}">`;q.options.forEach((x,i)=>{if(q.type==='kpi')h+=`<button class="kpi" data-i="${i}"><span>Indicador</span><b>${x[0]}</b><span>${x[1]}</span></button>`;else h+=`<button class="option" data-i="${i}">${String.fromCharCode(65+i)}. ${x}</button>`});h+='</div>';$('content').innerHTML=h;document.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>answer(+b.dataset.i));show('question');}
function answer(i){const q=qs[r];document.querySelectorAll('[data-i]').forEach(b=>b.disabled=true);if(i===q.answer){score+=r===2?40:30;rep+=r===0?20:15;$(`[data-i="${i}"]`).classList.add('correct');$('feedback').className='show ok';$('feedback').textContent='✓ '+q.ok}else{score+=5;rep+=3;$(`[data-i="${i}"]`).classList.add('wrong');$(`[data-i="${q.answer}"]`).classList.add('correct');$('feedback').className='show bad';$('feedback').textContent='✕ '+q.bad}$('score').textContent=score;$('next').classList.remove('hidden');$('next').textContent=r===2?'Ver resultado →':'Continuar →';}
function next(){if(r<2){r++;ad()}else result()}
function ad(){clearInterval(timer);let n=5;$('timer').textContent=n;$('continue').classList.add('hidden');show('ad');timer=setInterval(()=>{n--;$('timer').textContent=n;if(n<=0){clearInterval(timer);$('timer').textContent='✓';$('continue').classList.remove('hidden')}},1000)}
function result(){let rating=Math.min(4.9,4.1+score/100*.6).toFixed(1);$('finalScore').textContent=score+'/100';$('finalRating').textContent=rating+' ★';$('finalRep').textContent=Math.min(rep,100)+'%';$('resultTitle').textContent=score>=90?'¡Excelente diagnóstico!':score>=60?'¡Buen trabajo!':'Trivia completada';$('resultText').textContent='Analizaste el caso, identificaste un problema recurrente y seleccionaste una acción y un KPI para medir la mejora.';show('result')}
$('startBtn').onclick=start;$('next').onclick=next;$('continue').onclick=render;$('restart').onclick=start;
